server:
  session:
    # 8 hours timeout
    timeout: 28800

security:
  user:
    name: st
    password: 12
    role: USER

spring:
  data:
    mongodb:
      uri: mongodb://heroku_0087srhz:1svf4rlfhg93pj26348m6hn1pn@ds057816.mlab.com:57816/heroku_0087srhz

numberOfPagesToProcess: 30

#in milliseconds
processingInterval: 7200000

processorConfig:
  enabledProcessors:
    HALO_OGLASI:
      - PRODAJA
      - IZDAVANJE
    NEKRETNINE_RS:
      - PRODAJA
      - IZDAVANJE